import {
  BTN_LOGIN,
  BTN_REGISTER,
  TITLE_REGISTER,
  FORM_LABEL_EMAIL,
  FORM_LABEL_POLICY,
  BTN_SUBMIT_GENERIC,
} from './labelKeys';

export const LABELS_WELCOME = [
  BTN_LOGIN,
  BTN_REGISTER,
];

export const LABELS_REGISTER_ACCOUNT = [
  TITLE_REGISTER,
  FORM_LABEL_EMAIL,
  FORM_LABEL_POLICY,
  BTN_SUBMIT_GENERIC,
];
